### ISSUE TITLE
Saisie d'horaires pour une journée en particulier

### ISSUE THREAD

**Issue by guillett** [betagouv/annuaire-api#26]
Suite à l'email de @TOCQUEST.

> J’ai poursuivi l’intégration des différents CDAS sur GitHub.
>  
> J’ai une petite question pour certains CDAS qui restent à intégrer. Si je rajoute la spécifié ci-dessous (- le jeudi de 9h à 12h et de 14h30 à 17h)  est-ce que cela posera problème dans l’intégration ?
>  ```yaml
> accueil physique:
>   horaires:
>     - du: lundi
>       au: vendredi
>       heures:
>         - de: 9h
>           a: 12h
>         - de: 13h30
>           a: 17h
>         - le jeudi de 9h à 12h et de 14h30 à 17h
> ```

**Comment by guillett** [comment]
Pour le moment, cette proposition n'est pas valide.
Le bon format a utilisé est
```yaml
accueil physique:
  horaires:
    - du: lundi
      au: mercredi
      heures:
        - de: 9h
          a: 12h
        - de: 13h30
          a: 17h
    - du: jeudi
      au: jeudi
      heures:
        - de: 9h
          a: 12h
        - de: 14h30
          a: 17h
    - du: vendredi
      au: vendredi
      heures:
        - de: 9h
          a: 12h
        - de: 13h30
          a: 17h
```

Est-ce possible pour vous @TOCQUEST d'utiliser ce format ?

**Comment by TOCQUEST** [comment]
Oui pas de souci.  Dois-je apporter les modifications ? ou le faites-vous directement ?

**Comment by TOCQUEST** [comment]
J'ai apporté les modifications pour : 
- cdas_landerneau.yaml
- cdas_lesneven.yaml
- cdas_saint_renan.yaml
Bonne implémentation :+1

**Comment by TOCQUEST** [comment]
MERCI pour ces intégrations Thomas 👍 

En faisant des tests les communes du CDAS de Châteaulin ne remontent pas lors des simulations.
Une explication là-dessus ?

**Comment by guillett** [comment]
Il est passé à la trappe ce matin. C'est en cours d'intégration ! Désolé.

**Comment by guillett** [comment]
Le format a utilisé est indiqué dans [le commentaire suivant](https://github.com/betagouv/annuaire-api/issues/26#issuecomment-367630666).

```yaml
accueil physique:
  horaires:
    - du: jeudi
      au: jeudi
      heures:
        - de: 9h
          a: 12h
        - de: 14h30
          a: 17h
```
